const { loadStore } = require('../data/store');
const { PAGE_DEFINITIONS } = require('../constants');

const COMPANY_PROFILE = {
  name: 'Smart Summit for Training & Data Analysis',
  address: 'King Abdullah II St., Amman, Jordan',
  phone: '+962 7 9999 1111',
  email: 'finance@smartsummittda.com'
};

function normalizeType(type) {
  const normalized = String(type || '').toLowerCase();
  if (normalized === 'income' || normalized === 'expense') {
    return normalized;
  }
  throw new Error('Unsupported invoice type');
}

function escapePdfText(value) {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function buildContent(invoice) {
  const lines = [];
  const addText = (font, size, x, y, text) => {
    lines.push('BT');
    lines.push(`/${font} ${size} Tf`);
    lines.push(`${x} ${y} Td`);
    lines.push(`(${escapePdfText(text)}) Tj`);
    lines.push('ET');
  };

  addText('F1', 20, 72, 770, invoice.company.name);
  addText('F2', 12, 72, 748, invoice.company.address);
  addText('F2', 12, 72, 732, `Phone: ${invoice.company.phone}`);
  addText('F2', 12, 72, 716, `Email: ${invoice.company.email}`);
  addText('F1', 16, 400, 770, 'Official Invoice');
  addText('F2', 12, 400, 752, invoice.invoiceNumber);
  addText('F2', 12, 400, 736, invoice.date);

  addText('F1', 14, 72, 690, invoice.typeLabel);
  addText('F2', 12, 72, 670, `Page: ${invoice.pageLabel}`);
  addText('F2', 12, 72, 654, `Type: ${invoice.type === 'income' ? 'Payment received' : 'Payment made'}`);
  addText('F2', 12, 72, 638, `Party: ${invoice.partyName}`);

  const detailLines = [
    `Category: ${invoice.category}`,
    `Amount: ${invoice.amount.toFixed(2)} ${invoice.currency}`,
    `Payment method: ${invoice.paymentMethod}`,
    `Linked deal: ${invoice.linkedIncomeId || '—'}`
  ];
  detailLines.forEach((line, index) => {
    addText('F2', 12, 72, 610 - index * 16, line);
  });

  addText('F1', 13, 72, 540, 'Notes');
  const wrappedNotes = wrapText(invoice.notes || 'No additional notes provided.', 70);
  wrappedNotes.forEach((line, index) => {
    addText('F2', 11, 72, 520 - index * 14, line);
  });

  addText('F1', 13, 72, 460, 'Summary');
  addText('F2', 12, 72, 440, `Generated for record: ${invoice.id}`);
  addText('F2', 12, 72, 424, `Prepared on: ${new Date().toISOString().slice(0, 10)}`);

  addText(
    'F2',
    10,
    72,
    120,
    'This invoice was generated by Smart Summit Finance System – SSTDA.'
  );

  return lines.join('\n');
}

function wrapText(text, maxLength) {
  const words = text.split(/\s+/);
  const lines = [];
  let current = '';
  words.forEach((word) => {
    const tentative = current ? `${current} ${word}` : word;
    if (tentative.length > maxLength) {
      if (current) lines.push(current);
      current = word;
    } else {
      current = tentative;
    }
  });
  if (current) lines.push(current);
  return lines;
}

function buildPdfBuffer(invoice) {
  const content = buildContent(invoice);
  const contentLength = Buffer.byteLength(content, 'utf-8');
  const objects = [];
  objects.push('1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n');
  objects.push('2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n');
  objects.push(
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >> endobj\n'
  );
  objects.push('4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj\n');
  objects.push('5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n');
  objects.push(`6 0 obj << /Length ${contentLength} >> stream\n${content}\nendstream\nendobj\n`);

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((obj) => {
    offsets.push(Buffer.byteLength(pdf, 'utf-8'));
    pdf += obj;
  });
  const xrefOffset = Buffer.byteLength(pdf, 'utf-8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${offsets[i].toString().padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, 'utf-8');
}

function getInvoiceData(type, id) {
  const normalizedType = normalizeType(type);
  const store = loadStore();
  const collection = normalizedType === 'income' ? store.incomes : store.expenses;
  const record = collection.find((item) => item.id === id);
  if (!record) throw new Error('Record not found');
  const page = PAGE_DEFINITIONS[record.pageId] || { label: record.pageId };
  const typeLabel = normalizedType === 'income' ? 'Payment Received' : 'Payment Made';
  const partyName = normalizedType === 'income' ? record.clientName || 'Client' : record.notes || record.category;
  return {
    id: record.id,
    pageId: record.pageId,
    type: normalizedType,
    typeLabel,
    invoiceNumber: record.invoiceNumber,
    date: record.date,
    amount: record.amount,
    currency: 'JD',
    category: record.category,
    partyName,
    notes: record.notes || '',
    pageLabel: page.label,
    paymentMethod: record.paymentMethod || 'Pending',
    linkedIncomeId: record.linkedIncomeId || null,
    company: COMPANY_PROFILE
  };
}

function streamInvoicePdf(res, invoice) {
  const buffer = buildPdfBuffer(invoice);
  res.writeHead(200, {
    'Content-Type': 'application/pdf',
    'Content-Disposition': `attachment; filename="${invoice.invoiceNumber}.pdf"`
  });
  res.end(buffer);
}

module.exports = {
  getInvoiceData,
  streamInvoicePdf,
  COMPANY_PROFILE
};
