const { loadStore } = require('../data/store');
const { PAGE_DEFINITIONS } = require('../constants');

const COMPANY_PROFILE = {
  name: 'Smart Summit TDA Company',
  description: 'Training center in Irbid',
  address: 'Pr. Muhammad St., Irbid 00962',
  phones: ['+962 7 8009 2288', '+962 7 9912 7209'],
  email: 'smartsummitcompany@gmail.com'
};

function normalizeType(type) {
  const normalized = String(type || '').toLowerCase();
  if (normalized === 'income' || normalized === 'expense') {
    return normalized;
  }
  throw new Error('Unsupported invoice type');
}

function escapePdfText(value) {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function buildContent(invoice) {
  const lines = [];
  const addText = (font, size, x, y, text) => {
    lines.push('BT');
    lines.push(`/${font} ${size} Tf`);
    lines.push(`${x} ${y} Td`);
    lines.push(`(${escapePdfText(text)}) Tj`);
    lines.push('ET');
  };

  const headerTitle = invoice.type === 'income' ? 'Income Invoice' : 'Expense Report';
  addText('F1', 22, 60, 780, invoice.company.name);
  addText('F2', 12, 60, 760, invoice.company.description);
  addText('F2', 11, 60, 744, invoice.company.address);
  addText('F2', 11, 60, 728, `Phone: ${invoice.company.phones.join(' | ')}`);
  addText('F2', 11, 60, 712, `Email: ${invoice.company.email}`);

  addText('F1', 18, 360, 780, headerTitle);
  addText('F2', 12, 360, 760, `Invoice #: ${invoice.invoiceNumber}`);
  addText('F2', 12, 360, 744, `Date: ${invoice.date}`);
  addText('F2', 12, 360, 728, `Reference: ${invoice.id}`);

  let y = 680;
  addText('F1', 14, 60, y, 'Deal details');
  y -= 18;
  addText('F2', 12, 60, y, `Page: ${invoice.pageLabel}`);
  y -= 16;
  addText('F2', 12, 60, y, `Type: ${invoice.type === 'income' ? 'Payment received' : 'Payment made'}`);
  y -= 16;
  addText('F2', 12, 60, y, `Party: ${invoice.partyName}`);
  y -= 16;
  addText('F2', 12, 60, y, `Category: ${invoice.category}`);
  y -= 16;
  addText('F2', 12, 60, y, `Payment method: ${invoice.paymentMethod}`);
  y -= 16;
  addText('F2', 12, 60, y, `Linked deal: ${invoice.linkedIncomeId || '—'}`);

  y -= 26;
  addText('F1', 14, 60, y, invoice.type === 'income' ? 'Payment schedule' : 'Amount');
  y -= 18;
  if (invoice.type === 'income') {
    invoice.payments.forEach((payment, index) => {
      addText('F2', 12, 60, y, `Payment ${index + 1}: ${payment.date || 'N/A'} · ${payment.amount.toFixed(2)} ${invoice.currency}`);
      y -= 16;
    });
    addText('F2', 12, 60, y, `Total received: ${invoice.totalAmount.toFixed(2)} ${invoice.currency}`);
  } else {
    addText('F2', 12, 60, y, `${invoice.amount.toFixed(2)} ${invoice.currency}`);
  }

  y -= 32;
  addText('F1', 13, 60, y, 'Notes');
  y -= 18;
  const wrappedNotes = wrapText(invoice.notes || 'No additional notes provided.', 80);
  wrappedNotes.forEach((line, index) => {
    addText('F2', 11, 60, y - index * 14, line);
  });

  addText('F2', 11, 60, 130, 'This invoice was generated by Smart Summit Finance System – SSTDA.');
  addText('F2', 11, 60, 114, `${invoice.company.address} · ${invoice.company.phones.join(' / ')} · ${invoice.company.email}`);

  return lines.join('\n');
}

function wrapText(text, maxLength) {
  const words = text.split(/\s+/);
  const lines = [];
  let current = '';
  words.forEach((word) => {
    const tentative = current ? `${current} ${word}` : word;
    if (tentative.length > maxLength) {
      if (current) lines.push(current);
      current = word;
    } else {
      current = tentative;
    }
  });
  if (current) lines.push(current);
  return lines;
}

function buildPdfBuffer(invoice) {
  const content = buildContent(invoice);
  const contentLength = Buffer.byteLength(content, 'utf-8');
  const objects = [];
  objects.push('1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n');
  objects.push('2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n');
  objects.push(
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >> endobj\n'
  );
  objects.push('4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj\n');
  objects.push('5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n');
  objects.push(`6 0 obj << /Length ${contentLength} >> stream\n${content}\nendstream\nendobj\n`);

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((obj) => {
    offsets.push(Buffer.byteLength(pdf, 'utf-8'));
    pdf += obj;
  });
  const xrefOffset = Buffer.byteLength(pdf, 'utf-8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${offsets[i].toString().padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, 'utf-8');
}

function getInvoiceData(type, id) {
  const normalizedType = normalizeType(type);
  const store = loadStore();
  const collection = normalizedType === 'income' ? store.incomes : store.expenses;
  const record = collection.find((item) => item.id === id);
  if (!record) throw new Error('Record not found');
  const page = PAGE_DEFINITIONS[record.pageId] || { label: record.pageId };
  const typeLabel = normalizedType === 'income' ? 'Payment Received' : 'Payment Made';
  const partyName = normalizedType === 'income' ? record.clientName || 'Client' : record.notes || record.category;
  const payments =
    normalizedType === 'income'
      ? (record.payments && record.payments.length
          ? record.payments
          : [{ amount: record.amount, date: record.date }])
      : [{ amount: record.amount, date: record.date }];
  const totalAmount = payments.reduce((acc, payment) => acc + Number(payment.amount || 0), 0);
  return {
    id: record.id,
    pageId: record.pageId,
    type: normalizedType,
    typeLabel,
    invoiceNumber: record.invoiceNumber,
    date: record.date,
    amount: record.amount,
    currency: 'JD',
    category: record.category,
    partyName,
    notes: record.notes || '',
    pageLabel: page.label,
    paymentMethod: record.paymentMethod || 'Pending',
    linkedIncomeId: record.linkedIncomeId || null,
    company: COMPANY_PROFILE,
    payments: payments.map((payment) => ({
      amount: Number(payment.amount) || 0,
      date: payment.date || record.date
    })),
    totalAmount
  };
}

function streamInvoicePdf(res, invoice) {
  const buffer = buildPdfBuffer(invoice);
  res.writeHead(200, {
    'Content-Type': 'application/pdf',
    'Content-Disposition': `attachment; filename="${invoice.invoiceNumber}.pdf"`
  });
  res.end(buffer);
}

module.exports = {
  getInvoiceData,
  streamInvoicePdf,
  COMPANY_PROFILE
};
